title = "sample gitleaks config"

# This is a sample config file for gitleaks. You can configure gitleaks what to search for and what to whitelist.
# The output you are seeing here is the default gitleaks config. If GITLEAKS_CONFIG environment variable
# is set, gitleaks will load configurations from that path. If option --config-path is set, gitleaks will load
# configurations from that path. Gitleaks does not whitelist anything by default.

[[rules]]
	description = "AWS Secret Key"
	regex = '''ABCDE'''
	tags = ["key", "AWS"]

[[rules]]
    description = "AWS Access Key"
    regex = '''ABCDEF+c2L7yXeGvUyrPgYsDnWRRC1AYEXAMPLE'''
    tags = ["key", "AWS"]

